# -*- coding: utf-8 -*-
"""hybrid_federated_microgrid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T0fBmpKKMFZaoEFNCRftUwfscRcCSv4e
"""

# -*- coding: utf-8 -*-

"""MICROGRID STABILITY - HYBRID & FEDERATED LEARNING EXTENSION
============================================================
This script extends the main analysis with:
1. Stacking Ensemble (Hybrid Model)
2. LightGBM Classifier
3. LSTM (time-aware deep learning on raw windows)
4. Federated Learning simulation across microgrids

Run this AFTER generating X_train, X_test, y_train, y_test, X_train_s, X_test_s
from 'main_code_ml_final edit.py'.

"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, StackingClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score,
                             roc_auc_score, matthews_corrcoef, confusion_matrix)

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, BatchNormalization, Conv1D, MaxPooling1D, Flatten
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

import os
import time

"""============================================================
CONFIGURATION
============================================================

"""

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)
tf.random.set_seed(RANDOM_STATE)

OUTPUT_DIR = '/content/final_project_output_hybrid'
os.makedirs(OUTPUT_DIR, exist_ok=True)

print("="*60)
print("HYBRID MODELS & FEDERATED LEARNING")
print("="*60)

"""============================================================
SECTION 1: STACKING ENSEMBLE (HYBRID MODEL)
============================================================

"""

print("\n[1/4] Stacking Ensemble (Hybrid Model)...")

# Base estimators: top performers from your original run
base_estimators = [
    ('rf', RandomForestClassifier(n_estimators=100, max_depth=15, random_state=RANDOM_STATE,
                                   class_weight='balanced', n_jobs=-1)),
    ('svm_rbf', SVC(kernel='rbf', C=1.0, gamma='scale', probability=True,
                    random_state=RANDOM_STATE, class_weight='balanced')),
    ('gb', GradientBoostingClassifier(n_estimators=100, max_depth=5, learning_rate=0.1,
                                       random_state=RANDOM_STATE)),
    ('nb', GaussianNB())
]

# Meta-learner: Logistic Regression (simple, well-calibrated)
meta_learner = LogisticRegression(max_iter=500, random_state=RANDOM_STATE, class_weight='balanced')

stacking_model = StackingClassifier(
    estimators=base_estimators,
    final_estimator=meta_learner,
    cv=5,
    stack_method='predict_proba',  # use probabilities for meta-learner
    n_jobs=-1,
    passthrough=False  # set True to also pass raw features to meta-learner
)

t0 = time.time()
stacking_model.fit(X_train_s, y_train)  # Use scaled data for SVM
stack_time = time.time() - t0

y_pred_stack = stacking_model.predict(X_test_s)
y_prob_stack = stacking_model.predict_proba(X_test_s)[:, 1]

acc_stack = accuracy_score(y_test, y_pred_stack)
prec_stack = precision_score(y_test, y_pred_stack, zero_division=0)
rec_stack = recall_score(y_test, y_pred_stack, zero_division=0)
f1_stack = f1_score(y_test, y_pred_stack, zero_division=0)
mcc_stack = matthews_corrcoef(y_test, y_pred_stack)
roc_stack = roc_auc_score(y_test, y_prob_stack)

print(f"  Stacking -> Acc={acc_stack:.4f} F1={f1_stack:.4f} ROC={roc_stack:.4f} Time={stack_time:.2f}s")

stacking_results = {
    'Model': 'Stacking Ensemble (Hybrid)',
    'Accuracy': acc_stack, 'Precision': prec_stack, 'Recall': rec_stack,
    'F1-Score': f1_stack, 'ROC-AUC': roc_stack, 'MCC': mcc_stack, 'Train_Time_s': stack_time
}

with open('/content/main_code_ml_final_edit.py', 'r') as f:
    for line in f:
        if 'DATA_PATH' in line:
            print(line.strip())
            break

with open('/content/main_code_ml_final_edit.py', 'r') as f:
    print(f.read())

!python /content/main_code_ml_final\ edit.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/main_code_ml_final_edit.py
# # -*- coding: utf-8 -*-
# """Main_CODE_ML_.ipynb
# 
# Automatically generated by Colab.
# 
# Original file is located at
#     https://colab.research.google.com/drive/1gGuPD-n2KOBUIB_d2YzU67O-acvQt7fL
# 
# ============================================================
# MICROGRID SMALL-SIGNAL STABILITY ANALYSIS
# ML / DL Algorithm Comparison - Corrected Label Version
# ============================================================
# """
# 
# import sys
# import numpy as np
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# import warnings
# warnings.filterwarnings('ignore')
# 
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import StandardScaler
# from sklearn.metrics import (accuracy_score, precision_score, recall_score,
#                              f1_score, roc_auc_score, confusion_matrix,
#                              matthews_corrcoef, roc_curve)
# 
# from sklearn.linear_model import LogisticRegression
# from sklearn.svm import SVC
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.naive_bayes import GaussianNB
# from sklearn.tree import DecisionTreeClassifier
# from sklearn.ensemble import (RandomForestClassifier, AdaBoostClassifier,
#                               GradientBoostingClassifier)
# from sklearn.neural_network import MLPClassifier
# from xgboost import XGBClassifier
# 
# import os
# import time
# 
# """============================================================
# CONFIGURATION
# ============================================================
# 
# """
# 
# DATA_PATH = '/content/FINAL_microgrid_dataset_0.5s_REFORMED.csv' # Corrected path
# OUTPUT_DIR = '/content/final_project_output'
# RANDOM_STATE = 42
# SUBSAMPLE_EVERY = 3
# WINDOW_SIZE = 12
# STEP_SIZE = 6
# MAX_SAMPLES = 12000
# 
# os.makedirs(OUTPUT_DIR, exist_ok=True)
# np.random.seed(RANDOM_STATE)
# 
# 
# def load_data(data_path, random_state=42):
#     print(f"\n[1/5] Loading dataset from {data_path}...")
#     df = pd.read_csv(data_path)
# 
#     # Check if 'stability' column exists, if not, derive it
#     if 'stability' not in df.columns:
#         print("  'stability' column not found, deriving it from other features...")
# 
#         # Define bus names dynamically or explicitly
#         buses = sorted(list(set([col.split('_')[-1] for col in df.columns if 'voltage_pu_' in col]))) # e.g., ['MG1', 'MG2', 'MG3']
#         if not buses:
#           # Fallback if bus naming convention is different, assuming default MG1
#           buses = ['MG1'] if 'voltage_pu' in df.columns else []
# 
#         scores = []
#         # Iterate through the dataframe to calculate stability score for each row/window
#         # This is a simplified version for raw data, not windowed data.
#         for i in range(len(df)):
#             row = df.iloc[i]
#             bus_scores = []
#             for bus in buses:
#                 # Use default column names if bus-specific ones are not found
#                 voltage_col = f'voltage_pu_{bus}' if f'voltage_pu_{bus}' in df.columns else 'voltage_pu'
#                 freq_col = f'frequency_{bus}' if f'frequency_{bus}' in df.columns else 'frequency'
#                 rocof_col = f'rocof_{bus}' if f'rocof_{bus}' in df.columns else 'rocof'
#                 angle_col = f'angle_deg_{bus}' if f'angle_deg_{bus}' in df.columns else 'angle_deg'
#                 gen_p_col = f'gen_p_{bus}' if f'gen_p_{bus}' in df.columns else 'gen_p'
#                 load_p_col = f'load_p_{bus}' if f'load_p_{bus}' in df.columns else 'load_p'
#                 delay_col = f'delay_{bus}' if f'delay_{bus}' in df.columns else 'delay'
# 
#                 # Ensure columns exist for calculation
#                 if all(col in df.columns for col in [voltage_col, freq_col, rocof_col, angle_col]):
#                     v_score = max(0, 1 - abs(row[voltage_col] - 1.0) / 0.05)
#                     f_score = max(0, 1 - abs(row[freq_col] - 50.0) / 0.1)
#                     r_score = max(0, 1 - abs(row[rocof_col]) / 0.1)
#                     a_score = max(0, 1 - abs(row[angle_col]) / 10.0)
# 
#                     # Check for existence of gen_p, load_p, delay for p_score and d_score
#                     p_score = 1.0 # Default stable if no power data
#                     if gen_p_col in df.columns and load_p_col in df.columns:
#                         p_score = max(0, 1 - abs(row[gen_p_col] - row[load_p_col]) / 5.0)
# 
#                     d_score = 1.0 # Default stable if no delay data
#                     if delay_col in df.columns:
#                         d_score = max(0, 1 - row[delay_col] / 0.3)
# 
#                     bus_scores.append(np.mean([v_score, f_score, r_score, a_score, p_score, d_score]))
# 
#             inter_scores = []
#             # Example for inter-bus scores if applicable (adjust based on your actual data and needs)
#             # This part is highly dependent on your data structure, adapting a generic version
#             pair_combinations = [('MG1','MG2'), ('MG2','MG3'), ('MG1','MG3')] # Example pairs
#             for pair in pair_combinations:
#                 angle_deg_pair_0 = f'angle_deg_{pair[0]}'
#                 angle_deg_pair_1 = f'angle_deg_{pair[1]}'
#                 if angle_deg_pair_0 in df.columns and angle_deg_pair_1 in df.columns:
#                   diff = abs(row[angle_deg_pair_0] - row[angle_deg_pair_1])
#                   inter_scores.append(max(0, 1 - diff / 10.0))
# 
#             overall_score = np.mean(bus_scores + inter_scores) if (bus_scores + inter_scores) else 0.5 # Default to neutral if no scores
#             scores.append(overall_score)
# 
#         df['stability_score'] = scores
#         # Convert scores to binary stability (0 or 1)
#         # Using a percentile threshold, e.g., bottom 40% are unstable (0), top 60% are stable (1)
#         threshold = np.percentile(df['stability_score'], 40) # This threshold might need tuning
#         df['stability'] = (df['stability_score'] >= threshold).astype(int)
#         print(f"  Derived 'stability' column using threshold {threshold:.2f}. Stable samples: {df['stability'].sum()}/{len(df)}")
#         # Drop the intermediate stability_score if not needed
#         df = df.drop(columns=['stability_score'])
# 
#     # Ensure stability is integer type
#     df['stability'] = df['stability'].astype(int)
#     return df
# 
# 
# def preprocess_data(df, subsample_every=3):
#     print("[2/5] Preprocessing data (subsampling and feature engineering)...")
#     # Subsample to reduce data size and computational load
#     df_subsampled = df.iloc[::subsample_every, :].reset_index(drop=True)
# 
#     # Dynamically find bus names to create feature columns
#     # Identify columns that are NOT time, bus, or stability label itself
#     exclude_cols = ['time', 'bus', 'stability'] # 'bus' column should be dropped or one-hot encoded if it's a feature
#     feature_base_cols = [col for col in df_subsampled.columns if col not in exclude_cols and not col.endswith(('_MG1', '_MG2', '_MG3'))] # Avoid duplicating if already bus-specific
# 
#     # Handle bus column: one-hot encode if needed, or drop if it's just an identifier
#     if 'bus' in df_subsampled.columns:
#         # For simplicity, we'll drop 'bus' if it's just an identifier and features are already split by bus
#         # If 'bus' contains unique string identifiers like 'MG1', 'MG2', etc., it should be removed or one-hot encoded.
#         # Assuming features are already structured per bus (e.g., voltage_pu_MG1), so 'bus' column can be dropped
#         df_subsampled = df_subsampled.drop(columns=['bus'], errors='ignore')
# 
#     # Example of feature engineering for bus-specific features if they exist as separate columns
#     # This part should align with how your actual data is structured (e.g., if you have `voltage_pu` and `bus` column,
#     # or if you already have `voltage_pu_MG1`, `voltage_pu_MG2` as separate columns)
# 
#     # If original data had generic 'voltage_pu' and a 'bus' column, you might need to pivot or reshape here.
#     # For now, assuming the dataset structure is flat with features like voltage_pu, frequency, etc.
# 
#     # Separate features (X) and target (y)
#     X = df_subsampled.drop('stability', axis=1)
#     y = df_subsampled['stability']
# 
#     return X, y
# 
# 
# def create_time_series_features(df_features, df_labels, window_size=12, step_size=6, max_samples=12000):
#     print("[3/5] Creating time-series window features...")
#     features = []
#     labels = []
# 
#     # Identify columns that are not identifiers or labels
#     feature_cols = df_features.columns.tolist()
# 
#     n_samples_df = len(df_features)
#     # Loop through the DataFrame to create windows
#     for i in range(0, n_samples_df - window_size - 1, step_size):
#         window_df_features = df_features.iloc[i : i + window_size]
#         label = df_labels.iloc[i + window_size] # Label is from the end of the window
# 
#         if len(window_df_features) == window_size:
#             # For each feature in the window, calculate statistical summaries
#             window_features_summary = []
#             for col in feature_cols:
#                 window_features_summary.extend([
#                     window_df_features[col].mean(),
#                     window_df_features[col].std(),
#                     window_df_features[col].min(),
#                     window_df_features[col].max()
#                 ])
#             features.append(window_features_summary)
#             labels.append(label)
# 
#         if len(features) >= max_samples:
#             break
# 
#     X_ts = pd.DataFrame(features)
#     y_ts = pd.Series(labels)
# 
#     # Generate column names for the new features
#     new_feature_names = []
#     for col in feature_cols:
#         for stat in ['mean', 'std', 'min', 'max']:
#             new_feature_names.append(f'{col}_{stat}')
#     X_ts.columns = new_feature_names
# 
#     return X_ts, y_ts
# 
# 
# def train_evaluate_models(X_train, X_test, y_train, y_test, random_state=42):
#     print("[4/5] Training and evaluating models...")
#     models = {
#         'Logistic Regression': LogisticRegression(random_state=random_state, solver='liblinear'),
#         'SVM': SVC(random_state=random_state, probability=True),
#         'K-Nearest Neighbors': KNeighborsClassifier(),
#         'Naive Bayes': GaussianNB(),
#         'Decision Tree': DecisionTreeClassifier(random_state=random_state),
#         'Random Forest': RandomForestClassifier(random_state=random_state),
#         'AdaBoost': AdaBoostClassifier(random_state=random_state),
#         'Gradient Boosting': GradientBoostingClassifier(random_state=random_state),
#         'XGBoost': XGBClassifier(random_state=random_state, use_label_encoder=False, eval_metric='logloss'),
#         'MLP': MLPClassifier(random_state=random_state, max_iter=1000)
#     }
# 
#     results = []
#     for name, model in models.items():
#         print(f"  Training {name}...")
#         start_time = time.time()
#         model.fit(X_train, y_train)
#         train_time = time.time() - start_time
# 
#         y_pred = model.predict(X_test)
#         y_prob = model.predict_proba(X_test)[:, 1]
# 
#         accuracy = accuracy_score(y_test, y_pred)
#         precision = precision_score(y_test, y_pred, zero_division=0)
#         recall = recall_score(y_test, y_pred, zero_division=0)
#         f1 = f1_score(y_test, y_pred, zero_division=0)
#         roc_auc = roc_auc_score(y_test, y_prob)
#         mcc = matthews_corrcoef(y_test, y_pred)
# 
#         results.append({
#             'Model': name,
#             'Accuracy': accuracy,
#             'Precision': precision,
#             'Recall': recall,
#             'F1-Score': f1,
#             'ROC-AUC': roc_auc,
#             'MCC': mcc,
#             'Train_Time_s': train_time
#         })
#     return pd.DataFrame(results), models
# 
# 
# def main():
#     df = load_data(DATA_PATH, RANDOM_STATE)
#     X_pre, y_pre = preprocess_data(df, SUBSAMPLE_EVERY) # X_pre are features, y_pre are labels
#     X_ts, y_ts = create_time_series_features(X_pre, y_pre, WINDOW_SIZE, STEP_SIZE, MAX_SAMPLES) # Pass both features and labels
# 
#     print("[5/5] Splitting and scaling data...")
#     # Split data for ML models
#     X_train, X_test, y_train, y_test = train_test_split(X_ts, y_ts, test_size=0.2, random_state=RANDOM_STATE, stratify=y_ts)
# 
#     # Scale features
#     scaler = StandardScaler()
#     X_train_s = scaler.fit_transform(X_train)
#     X_test_s = scaler.transform(X_test)
# 
#     # Convert back to DataFrame with column names if needed for specific models or interpretation
#     X_train_s = pd.DataFrame(X_train_s, columns=X_train.columns)
#     X_test_s = pd.DataFrame(X_test_s, columns=X_test.columns)
# 
#     # Store X_train, X_test, y_train, y_test, X_train_s, X_test_s in global scope
#     global X_train_global, X_test_global, y_train_global, y_test_global, X_train_s_global, X_test_s_global
#     X_train_global = X_train
#     X_test_global = X_test
#     y_train_global = y_train
#     y_test_global = y_test
#     X_train_s_global = X_train_s
#     X_test_s_global = X_test_s
# 
#     results_df, models = train_evaluate_models(X_train_s, X_test_s, y_train, y_test, RANDOM_STATE)
# 
#     results_df = results_df.sort_values(by='F1-Score', ascending=False).reset_index(drop=True)
# 
#     print("\n" + "="*60)
#     print("MODEL COMPARISON RESULTS")
#     print("="*60)
#     print(results_df.to_string(index=False))
# 
#     results_df.to_csv(os.path.join(OUTPUT_DIR, 'model_comparison_results.csv'), index=False)
#     print(f"\nFull results saved to: {OUTPUT_DIR}/model_comparison_results.csv")
# 
#     # For the hybrid script to access these variables, they need to be defined in the global namespace
#     # Or passed as arguments, but for Colab interactive use, defining them globally after running the script is common
#     import builtins
#     builtins.X_train = X_train
#     builtins.X_test = X_test
#     builtins.y_train = y_train
#     builtins.y_test = y_test
#     builtins.X_train_s = X_train_s
#     builtins.X_test_s = X_test_s
#     builtins.df_wide = X_pre # X_pre is the preprocessed wide dataframe before windowing
# 
#     # Determine bus names dynamically based on columns in X_pre
#     unique_bus_suffixes = sorted(list(set([col.split('_')[-1] for col in X_pre.columns if '_' in col and not col.endswith(('mean', 'std', 'min', 'max'))]))) # Heuristic to find bus suffixes
#     if unique_bus_suffixes:
#       buses_for_export = [f'MG{i}' for i in range(1, len(unique_bus_suffixes) + 1)] if all(s.startswith('MG') for s in unique_bus_suffixes) else unique_bus_suffixes # Try to keep MG1, MG2 etc if format is consistent
#     else:
#       buses_for_export = ['MG1'] # Fallback to a single generic bus if no bus-specific columns found
# 
#     builtins.buses = buses_for_export
#     builtins.results_df = results_df # To potentially use for visualization in subsequent cells
#     builtins.models = models # To access best model details later
# 
#     # Ensure the required variables are made global if the script is run directly
#     # This is a common pattern in notebooks when running external scripts meant to populate the workspace
#     globals()['X_train'] = X_train
#     globals()['X_test'] = X_test
#     globals()['y_train'] = y_train
#     globals()['y_test'] = y_test
#     globals()['X_train_s'] = X_train_s
#     globals()['X_test_s'] = X_test_s
#     globals()['df_wide'] = X_pre
#     globals()['buses'] = buses_for_export
#     globals()['results_df'] = results_df
#     globals()['models'] = models
# 
# 
# 
#     """### Plot 1: F1-Score and ROC-AUC Comparison
# 
#     """
# 
#     plt.figure(figsize=(12, 6))
#     metrics = ['Accuracy', 'F1-Score', 'ROC-AUC', 'MCC']
#     num_metrics = len(metrics)
#     bar_width = 0.2
#     index = np.arange(len(results_df['Model']))
# 
#     for i, metric in enumerate(metrics):
#         plt.bar(index + i * bar_width, results_df[metric], bar_width, label=metric)
# 
#     plt.xlabel('Model', fontsize=12)
#     plt.ylabel('Score', fontsize=12)
#     plt.title('Model Performance Comparison (F1-Score, ROC-AUC, Accuracy, MCC)', fontsize=14, fontweight='bold')
#     plt.xticks(index + num_metrics * bar_width / 2 - bar_width / 2, results_df['Model'], rotation=45, ha='right')
#     plt.ylim([0, 1.05])
#     plt.legend(loc='lower right')
#     plt.tight_layout()
#     plt.savefig(os.path.join(OUTPUT_DIR, 'model_performance_comparison.png'), dpi=300, bbox_inches='tight')
#     plt.close()
# 
#     """### Plot 2: ROC Curves
# 
#     """
# 
#     plt.figure(figsize=(10, 8))
#     for name, model in models.items():
#         y_prob = model.predict_proba(X_test_s)[:, 1] # Use scaled data for prediction
#         fpr, tpr, _ = roc_curve(y_test, y_prob)
#         plt.plot(fpr, tpr, label=f'{name} (AUC = {roc_auc_score(y_test, y_prob):.2f})')
# 
#     plt.plot([0, 1], [0, 1], 'k--', label='Random Classifier')
#     plt.xlabel('False Positive Rate', fontsize=12)
#     plt.ylabel('True Positive Rate', fontsize=12)
#     plt.title('ROC Curves for All Models', fontsize=14, fontweight='bold')
#     plt.legend(loc='lower right')
#     plt.grid(alpha=0.3)
#     plt.tight_layout()
#     plt.savefig(os.path.join(OUTPUT_DIR, 'roc_curves.png'), dpi=300, bbox_inches='tight')
#     plt.close()
# 
#     """### Plot 3: Heatmap
# 
#     """
# 
#     plt.figure(figsize=(8, 7))
#     hm = results_df.set_index('Model')[metrics].sort_values('F1-Score', ascending=True)
#     sns.heatmap(hm, annot=True, fmt='.3f', cmap='RdYlGn', vmin=0, vmax=1, linewidths=0.5)
#     plt.title('Performance Heatmap', fontsize=14, fontweight='bold')
#     plt.tight_layout()
#     plt.savefig(os.path.join(OUTPUT_DIR, 'performance_heatmap.png'), dpi=300, bbox_inches='tight')
#     plt.close()
# 
#     """### Plot 4: Train time
# 
#     """
# 
#     plt.figure(figsize=(10, 6))
#     plt.barh(results_df['Model'], results_df['Train_Time_s'], color='coral', edgecolor='darkred')
#     plt.xlabel('Training Time (seconds)', fontsize=12)
#     plt.title('Training Time Comparison', fontsize=14, fontweight='bold')
#     plt.gca().invert_yaxis()
#     plt.grid(axis='x', alpha=0.3)
#     plt.tight_layout()
#     plt.savefig(os.path.join(OUTPUT_DIR, 'train_time.png'), dpi=300, bbox_inches='tight')
#     plt.close()
# 
#     """### Plot 5: Confusion matrix (best model)
# 
#     """
# 
#     best_name = results_df.iloc[0]['Model']
#     best_model = models[best_name]
#     # Ensure correct data is passed to predict, scaled or unscaled based on model type requirements
#     X_te = X_test.values if best_name in ['Random Forest','Decision Tree','AdaBoost','Gradient Boosting','XGBoost','Naive Bayes'] else X_test_s # Use X_test_s for scaled models
#     y_pred_best = best_model.predict(X_te)
#     cm = confusion_matrix(y_test, y_pred_best)
#     plt.figure(figsize=(5, 4))
#     sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Unstable','Stable'], yticklabels=['Unstable','Stable'])
#     plt.title(f'Best Model: {best_name}', fontsize=13, fontweight='bold')
#     plt.ylabel('True Label', fontsize=11)
#     plt.xlabel('Predicted Label', fontsize=11)
#     plt.tight_layout()
#     plt.savefig(os.path.join(OUTPUT_DIR, 'confusion_matrix.png'), dpi=300, bbox_inches='tight')
#     plt.close()
# 
#     print("\n" + "="*60, flush=True)
#     print("FINAL SUMMARY", flush=True)
#     print("="*60, flush=True)
#     print(results_df[['Model','Accuracy','F1-Score','ROC-AUC','MCC']].head(5).to_string(index=False), flush=True)
#     print(f"\nBest Model: {best_name}", flush=True)
#     print(f"  Accuracy:  {results_df.iloc[0]['Accuracy']:.4f}", flush=True)
#     print(f"  F1-Score:  {results_df.iloc[0]['F1-Score']:.4f}", flush=True)
#     print(f"  ROC-AUC:   {results_df.iloc[0]['ROC-AUC']:.4f}", flush=True)
#     print(f"  MCC:       {results_df.iloc[0]['MCC']:.4f}", flush=True)
#     print(f"\nAll outputs saved to: {OUTPUT_DIR}", flush=True)
#     print("="*60, flush=True)
# 
# 
# if __name__ == '__main__':
#     main()
#

"""The `main_code_ml_final_edit.py` script has been updated. Let's re-run it to load the data, derive the 'stability' column, and define the necessary `X_train`, `y_train`, `X_train_s`, and `X_test_s` variables."""

!python /content/main_code_ml_final_edit.py

!python /content/main_code_ml_final_edit.py

!python /content/main_code_ml_final_edit.py

"""Now that the `FINAL_microgrid_dataset_0.5s_REFORMED.csv` file is uploaded, we need to re-run the `main_code_ml_final_edit.py` script to properly load the data and define `X_train`, `y_train`, `X_train_s`, and other necessary variables in the environment. This script also performs initial model training and evaluation."""

!python /content/main_code_ml_final_edit.py

"""The `KeyError: 'stability'` indicates that the `main_code_ml_final_edit.py` script cannot find a column named 'stability' in your uploaded CSV file. Let's inspect the columns of the `FINAL_microgrid_dataset_0.5s_REFORMED.csv` to ensure the column name is correct."""

import pandas as pd

data_path = '/content/FINAL_microgrid_dataset_0.5s_REFORMED.csv'
try:
    # Read the CSV file into a DataFrame
    df_check_cols = pd.read_csv(data_path)

    # Print all column names
    print("Columns in the uploaded CSV file:")
    for col in df_check_cols.columns:
        print(f"- {col}")

    # You can also display the first few rows to see the data content
    print("\nFirst 5 rows of the data:")
    display(df_check_cols.head())

except FileNotFoundError:
    print(f"Error: The file {data_path} was not found. Please ensure it's uploaded to /content/.")
except Exception as e:
    print(f"An error occurred while reading the CSV: {e}")

!python /content/main_code_ml_final_edit.py

"""============================================================
SECTION 2: LIGHTGBM
============================================================

"""

print("\n[2/4] LightGBM...")
try:
    import lightgbm as lgb

    lgb_model = lgb.LGBMClassifier(
        n_estimators=200,
        max_depth=8,
        learning_rate=0.05,
        num_leaves=31,
        subsample=0.8,
        colsample_bytree=0.8,
        class_weight='balanced',
        random_state=RANDOM_STATE,
        n_jobs=-1,
        verbosity=-1
    )

    t0 = time.time()
    lgb_model.fit(X_train.values, y_train)
    lgb_time = time.time() - t0

    y_pred_lgb = lgb_model.predict(X_test.values)
    y_prob_lgb = lgb_model.predict_proba(X_test.values)[:, 1]

    acc_lgb = accuracy_score(y_test, y_pred_lgb)
    prec_lgb = precision_score(y_test, y_pred_lgb, zero_division=0)
    rec_lgb = recall_score(y_test, y_pred_lgb, zero_division=0)
    f1_lgb = f1_score(y_test, y_pred_lgb, zero_division=0)
    mcc_lgb = matthews_corrcoef(y_test, y_pred_lgb)
    roc_lgb = roc_auc_score(y_test, y_prob_lgb)

    print(f"  LightGBM -> Acc={acc_lgb:.4f} F1={f1_lgb:.4f} ROC={roc_lgb:.4f} Time={lgb_time:.2f}s")

    lgb_results = {
        'Model': 'LightGBM',
        'Accuracy': acc_lgb, 'Precision': prec_lgb, 'Recall': rec_lgb,
        'F1-Score': f1_lgb, 'ROC-AUC': roc_lgb, 'MCC': mcc_lgb, 'Train_Time_s': lgb_time
    }
except ImportError:
    print("  LightGBM not installed. Install with: pip install lightgbm")
    lgb_results = None

"""============================================================
SECTION 3: LSTM (Deep Learning on Raw Time Windows)
============================================================

"""

print("\n[3/4] LSTM on raw window sequences...")

"""To run LSTM, we need to reconstruct the raw window sequences.
The original code extracted statistical features. We need to go back to raw windows.
If you have the raw window data saved, load it. Otherwise, we reconstruct from df_wide.

"""



"""NOTE: This section assumes you have access to the original df_wide from the main script.
If df_wide is not in memory, you need to rerun the windowing loop without feature extraction.

"""

def build_lstm_data(df_wide, window_size=12, step_size=6, max_samples=12000):

"""    Build 3D array (samples, timesteps, features) for LSTM from df_wide.
    

"""

feature_cols = [c for c in df_wide.columns if c != 'time']
    X_seq, y_seq = [], []
    n = len(df_wide)

    for i in range(0, n - 2*window_size, step_size):
        window = df_wide.iloc[i:i+window_size][feature_cols].values
        future = df_wide.iloc[i+window_size:i+2*window_size]

        # Compute stability label using same logic as main code
        bus_scores = []
        for bus in buses:
            v = future[f'voltage_pu_{bus}'].values
            f = future[f'frequency_{bus}'].values
            r = future[f'rocof_{bus}'].values
            a = future[f'angle_deg_{bus}'].values
            g = future[f'gen_p_{bus}'].values
            l = future[f'load_p_{bus}'].values
            d = future[f'delay_{bus}'].values

            v_score = max(0, 1 - np.max(np.abs(v - 1.0)) / 0.05)
            f_score = max(0, 1 - np.max(np.abs(f - 50.0)) / 0.1)
            r_score = max(0, 1 - np.max(np.abs(r)) / 0.1)
            a_score = max(0, 1 - np.max(np.abs(a)) / 10.0)
            p_score = max(0, 1 - np.mean(np.abs(g - l)) / 5.0)
            d_score = max(0, 1 - np.mean(d) / 0.3)
            bus_scores.append(np.mean([v_score, f_score, r_score, a_score, p_score, d_score]))

        inter_scores = []
        for pair in [('MG1','MG2'), ('MG2','MG3'), ('MG1','MG3')]:
            if f'angle_deg_{pair[0]}' in df_wide.columns and f'angle_deg_{pair[1]}' in df_wide.columns:
                a1 = future[f'angle_deg_{pair[0]}'].values
                a2 = future[f'angle_deg_{pair[1]}'].values
                diff = np.max(np.abs(a1 - a2))
                inter_scores.append(max(0, 1 - diff / 10.0))

        pimb = np.mean(np.abs(future['total_power_imbalance'].values)) if 'total_power_imbalance' in future.columns else 0
        pimb_score = max(0, 1 - pimb / 5.0)
        overall_score = np.mean(bus_scores + inter_scores + [pimb_score])

        X_seq.append(window)
        y_seq.append(overall_score)

        if len(X_seq) >= max_samples:
            break

    X_seq = np.array(X_seq)
    scores_seq = np.array(y_seq)
    threshold = np.percentile(scores_seq, 60)
    y_seq = np.where(scores_seq >= threshold, 1, 0)

    return X_seq, y_seq, scores_seq

# Only run LSTM if df_wide is available in memory
try:
    X_seq, y_seq, scores_seq = build_lstm_data(df_wide, window_size=12, step_size=6, max_samples=12000)

    from sklearn.model_selection import train_test_split
    X_seq_train, X_seq_test, y_seq_train, y_seq_test = train_test_split(
        X_seq, y_seq, test_size=0.2, random_state=RANDOM_STATE, stratify=y_seq
    )

    # Normalize features per channel
    n_samples, n_timesteps, n_features = X_seq_train.shape
    X_seq_train_flat = X_seq_train.reshape(-1, n_features)
    X_seq_test_flat = X_seq_test.reshape(-1, n_features)

    from sklearn.preprocessing import StandardScaler
    seq_scaler = StandardScaler()
    X_seq_train_s = seq_scaler.fit_transform(X_seq_train_flat).reshape(n_samples, n_timesteps, n_features)
    X_seq_test_s = seq_scaler.transform(X_seq_test_flat).reshape(-1, n_timesteps, n_features)

    # Build LSTM model
    lstm_model = Sequential([
        LSTM(64, return_sequences=True, input_shape=(n_timesteps, n_features)),
        Dropout(0.2),
        BatchNormalization(),
        LSTM(32, return_sequences=False),
        Dropout(0.2),
        Dense(16, activation='relu'),
        Dropout(0.2),
        Dense(1, activation='sigmoid')
    ])

    lstm_model.compile(optimizer=keras.optimizers.Adam(learning_rate=0.001),
                       loss='binary_crossentropy',
                       metrics=['accuracy'])

    early_stop = EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)
    lr_reduce = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=5, min_lr=1e-6)

    t0 = time.time()
    history = lstm_model.fit(
        X_seq_train_s, y_seq_train,
        validation_split=0.1,
        epochs=100,
        batch_size=64,
        callbacks=[early_stop, lr_reduce],
        verbose=0
    )
    lstm_time = time.time() - t0

    y_prob_lstm = lstm_model.predict(X_seq_test_s, verbose=0).flatten()
    y_pred_lstm = (y_prob_lstm >= 0.5).astype(int)

    acc_lstm = accuracy_score(y_seq_test, y_pred_lstm)
    prec_lstm = precision_score(y_seq_test, y_pred_lstm, zero_division=0)
    rec_lstm = recall_score(y_seq_test, y_pred_lstm, zero_division=0)
    f1_lstm = f1_score(y_seq_test, y_pred_lstm, zero_division=0)
    mcc_lstm = matthews_corrcoef(y_seq_test, y_pred_lstm)
    roc_lstm = roc_auc_score(y_seq_test, y_prob_lstm)

    print(f"  LSTM -> Acc={acc_lstm:.4f} F1={f1_lstm:.4f} ROC={roc_lstm:.4f} Time={lstm_time:.2f}s")
    print(f"  Epochs trained: {len(history.history['loss'])}")

    lstm_results = {
        'Model': 'LSTM',
        'Accuracy': acc_lstm, 'Precision': prec_lstm, 'Recall': rec_lstm,
        'F1-Score': f1_lstm, 'ROC-AUC': roc_lstm, 'MCC': mcc_lstm, 'Train_Time_s': lstm_time
    }

except NameError as e:
    print(f"  Skipping LSTM (df_wide not in memory): {e}")
    lstm_results = None
except Exception as e:
    print(f"  LSTM error: {e}")
    lstm_results = None

"""============================================================
SECTION 4: FEDERATED LEARNING SIMULATION
============================================================

"""

print("\n[4/4] Federated Learning Simulation...")
print("  (This is a simulation using sklearn to demonstrate the concept)")

"""FEDERATED LEARNING FOR MICROGRID STABILITY
-------------------------------------------
Why it fits:
  - Multiple microgrids (MG1, MG2, MG3) generate data locally.
  - Privacy/communication constraints: raw data shouldn't leave each MG.
  - Federated Averaging (FedAvg) lets each MG train locally, then aggregate
    only model weights (not data) at a central server.

Architecture:
  - 3 Clients = MG1, MG2, MG3 (each has local training data)
  - 1 Server = Aggregates model updates
  - Communication rounds = 10
  - Model = RandomForest (for sklearn demo) or Neural Network (for TF/PyTorch)

"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.base import clone
from collections import Counter

def split_data_by_bus(df, buses, feature_cols, window_size=12, step_size=6, max_per_client=4000):

"""    Simulate each bus as a federated client with local data.
    Each client gets data that is predominantly from one bus + some overlap.
    

"""

client_datasets = {}
    for bus in buses:
        # Create a subset biased toward this bus's features
        bus_features = [c for c in df.columns if c != 'time' and bus in c]
        other_features = [c for c in df.columns if c != 'time' and bus not in c]

        # Simple split: each client gets a different time slice
        start_idx = buses.index(bus) * (len(df) // len(buses))
        end_idx = start_idx + len(df) // len(buses)
        client_df = df.iloc[start_idx:end_idx].copy()

        client_datasets[bus] = client_df
    return client_datasets

def federated_avg(models, weights=None):

"""    For tree-based models, true FedAvg is hard. We simulate by:
    1. Majority voting on predictions, or
    2. Retraining a new model on aggregated predictions (knowledge distillation)

    For neural networks, we would average weights directly.
    Here we use an ensemble-voting approach as a proxy.
    

"""

# Return a voting ensemble of client models
    from sklearn.ensemble import VotingClassifier
    estimators = [(f'client_{i}', m) for i, m in enumerate(models)]
    voting = VotingClassifier(estimators=estimators, voting='soft')

"""VotingClassifier needs to be fit, but we can't fit it on nothing.
Instead, we'll use the models to predict and average probabilities.

"""

return models

def simulate_federated_learning(X_train, y_train, X_test, y_test, buses, n_rounds=10):

"""    Simulate FedAvg with RandomForest as the local model.
    

"""

# Split training data among clients (simulated by non-overlapping samples)
    n_clients = len(buses)
    client_size = len(X_train) // n_clients
    client_indices = [range(i*client_size, (i+1)*client_size) for i in range(n_clients)]

    # Initialize global model
    global_model = RandomForestClassifier(n_estimators=50, max_depth=10,
                                           random_state=RANDOM_STATE, class_weight='balanced',
                                           n_jobs=-1)

    # Simulate local training + aggregation rounds
    all_val_accs = []

    for round_num in range(n_rounds):
        client_models = []
        round_accs = []

        for i, idx in enumerate(client_indices):
            X_local = X_train.iloc[list(idx)].values
            y_local = y_train.iloc[list(idx)]

            # Local training: clone global model and fine-tune
            local_model = clone(global_model)
            local_model.fit(X_local, y_local)

            # Local validation
            local_acc = accuracy_score(y_test, local_model.predict(X_test.values))
            round_accs.append(local_acc)
            client_models.append(local_model)

"""Aggregate: Ensemble voting (proxy for weight averaging with trees)
For true FedAvg with trees, use FedForest or Neural Networks instead.
Here we use soft voting by averaging probabilities.

"""

y_prob_global = np.mean([m.predict_proba(X_test.values)[:, 1] for m in client_models], axis=0)
        y_pred_global = (y_prob_global >= 0.5).astype(int)
        global_acc = accuracy_score(y_test, y_pred_global)

        all_val_accs.append(global_acc)

        # Update global model for next round (select best client as new global)
        best_client = client_models[np.argmax(round_accs)]
        global_model = clone(best_client)

        if round_num % 3 == 0 or round_num == n_rounds - 1:
            print(f"    Round {round_num+1:2d}: Local Accs={[f'{a:.4f}' for a in round_accs]}, Global Acc={global_acc:.4f}")

    return global_model, all_val_accs

# Run FL simulation (only if X_train, y_train exist)
try:
    print("  Running Federated Averaging simulation across 3 microgrids...")
    fl_model, fl_history = simulate_federated_learning(
        X_train, y_train, X_test, y_test, buses, n_rounds=10
    )

    print(f"\n  FL Final Accuracy: {fl_history[-1]:.4f}")
    print(f"  FL Accuracy progression: {[f'{a:.4f}' for a in fl_history]}")

    # Plot FL convergence
    plt.figure(figsize=(8, 5))
    plt.plot(range(1, len(fl_history)+1), fl_history, marker='o', linewidth=2, color='darkblue')
    plt.xlabel('Communication Round', fontsize=12)
    plt.ylabel('Global Test Accuracy', fontsize=12)
    plt.title('Federated Learning Convergence (Microgrid Simulation)', fontsize=14, fontweight='bold')
    plt.ylim([0.85, 1.0])
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, 'federated_learning_convergence.png'), dpi=300, bbox_inches='tight')
    plt.close()
    print(f"  Saved: {OUTPUT_DIR}/federated_learning_convergence.png")

except NameError as e:
    print(f"  Skipping FL simulation (data not in memory): {e}")

"""============================================================
SUMMARY COMPARISON
============================================================

"""

print("\n" + "="*60)
print("HYBRID MODEL COMPARISON")
print("="*60)

all_results = [stacking_results]
if lgb_results:
    all_results.append(lgb_results)
if lstm_results:
    all_results.append(lstm_results)

hybrid_df = pd.DataFrame(all_results).sort_values('F1-Score', ascending=False).reset_index(drop=True)
print(hybrid_df[['Model', 'Accuracy', 'F1-Score', 'ROC-AUC', 'MCC', 'Train_Time_s']].to_string(index=False))

hybrid_df.to_csv(os.path.join(OUTPUT_DIR, 'hybrid_model_results.csv'), index=False)
print(f"\nSaved to: {OUTPUT_DIR}/hybrid_model_results.csv")

"""============================================================
VISUALIZATION: BEFORE vs AFTER
============================================================

"""

print("\nGenerating comparison plot...")

# If you have the original results loaded:
orig_results_path = '/content/final_project_output/model_comparison_results.csv'
if os.path.exists(orig_results_path):
    orig_df = pd.read_csv(orig_results_path)
    combined = pd.concat([orig_df[['Model', 'F1-Score', 'ROC-AUC']], hybrid_df[['Model', 'F1-Score', 'ROC-AUC']]], ignore_index=True)
    combined = combined.sort_values('F1-Score', ascending=False).head(10)

    plt.figure(figsize=(12, 6))
    x = np.arange(len(combined))
    width = 0.35
    plt.bar(x - width/2, combined['F1-Score'], width, label='F1-Score', color='steelblue')
    plt.bar(x + width/2, combined['ROC-AUC'], width, label='ROC-AUC', color='coral')
    plt.xticks(x, combined['Model'], rotation=45, ha='right')
    plt.ylabel('Score', fontsize=12)
    plt.title('Top 10 Models: Original + Hybrid', fontsize=14, fontweight='bold')
    plt.legend()
    plt.ylim([0.85, 1.0])
    plt.grid(axis='y', alpha=0.3)
    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, 'combined_comparison.png'), dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Saved: {OUTPUT_DIR}/combined_comparison.png")

print("\n" + "="*60)
print("DONE")
print("="*60)