# -*- coding: utf-8 -*-
"""Main_CODE_ML_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gGuPD-n2KOBUIB_d2YzU67O-acvQt7fL

============================================================
MICROGRID SMALL-SIGNAL STABILITY ANALYSIS
ML / DL Algorithm Comparison - Corrected Label Version
============================================================
"""

import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, roc_auc_score, confusion_matrix,
                             matthews_corrcoef, roc_curve)

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import (RandomForestClassifier, AdaBoostClassifier,
                              GradientBoostingClassifier)
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier

import os
import time

"""============================================================
CONFIGURATION
============================================================

"""

DATA_PATH = '/FINAL_microgrid_dataset_0.5s_REFORMED.csv'
OUTPUT_DIR = '/content/final_project_output'
RANDOM_STATE = 42
SUBSAMPLE_EVERY = 3
WINDOW_SIZE = 12
STEP_SIZE = 6
MAX_SAMPLES = 12000

os.makedirs(OUTPUT_DIR, exist_ok=True)
np.random.seed(RANDOM_STATE)

print("="*60, flush=True)
print("MICROGRID STABILITY ANALYSIS - ML/DL COMPARISON", flush=True)
print("="*60, flush=True)

"""============================================================
1. LOAD DATA
============================================================

"""

print("\n[1/5] Loading dataset...", flush=True)
df = pd.read_csv(DATA_PATH)
print(f"Original: {df.shape}, subsample every {SUBSAMPLE_EVERY}th row", flush=True)
df = df.iloc[::SUBSAMPLE_EVERY].copy()
print(f"After subsample: {df.shape}", flush=True)

buses = sorted(df['bus'].unique())
print(f"Buses: {buses}", flush=True)

print('\nBus distribution in the loaded DataFrame:')
display(df['bus'].value_counts())

"""============================================================
2. WIDE FORMAT
============================================================

"""

print("\n[2/5] Reshaping to wide format...", flush=True)

feature_cols = ['voltage_pu', 'angle_deg', 'frequency', 'rocof',
                'gen_p', 'load_p', 'tie_line_power', 'delay']

df_wide = df.pivot_table(index='time', columns='bus', values=feature_cols)
df_wide.columns = [f"{col[0]}_{col[1]}" for col in df_wide.columns] # Flatten MultiIndex
df_wide = df_wide.reset_index()

# Calculate differences only for existing buses
if 'MG1' in buses and 'MG2' in buses:
    for feat in ['voltage_pu', 'angle_deg', 'frequency']:
        df_wide[f'{feat}_diff_MG1_MG2'] = df_wide[f'{feat}_MG1'] - df_wide[f'{feat}_MG2']
if 'MG2' in buses and 'MG3' in buses:
    for feat in ['voltage_pu', 'angle_deg', 'frequency']:
        df_wide[f'{feat}_diff_MG2_MG3'] = df_wide[f'{feat}_MG2'] - df_wide[f'{feat}_MG3']
if 'MG1' in buses and 'MG3' in buses:
    for feat in ['voltage_pu', 'angle_deg', 'frequency']:
        df_wide[f'{feat}_diff_MG1_MG3'] = df_wide[f'{feat}_MG1'] - df_wide[f'{feat}_MG3']

# Reconstruct total and average values based on available buses dynamically
total_gen_p_sum = []
total_load_p_sum = []
total_delay_sum = [] # For average calculation

for b in buses:
    if f'gen_p_{b}' in df_wide.columns:
        total_gen_p_sum.append(df_wide[f'gen_p_{b}'])
    if f'load_p_{b}' in df_wide.columns:
        total_load_p_sum.append(df_wide[f'load_p_{b}'])
    if f'delay_{b}' in df_wide.columns:
        total_delay_sum.append(df_wide[f'delay_{b}'])

df_wide['total_gen_p'] = sum(total_gen_p_sum) if total_gen_p_sum else 0
df_wide['total_load_p'] = sum(total_load_p_sum) if total_load_p_sum else 0
df_wide['total_power_imbalance'] = df_wide['total_gen_p'] - df_wide['total_load_p']
df_wide['avg_delay'] = sum(total_delay_sum) / len(total_delay_sum) if total_delay_sum else 0

print(f"Wide shape: {df_wide.shape}", flush=True)

"""============================================================
3. WINDOWS & COMPOSITE STABILITY LABEL
============================================================

"""

print(f"\n[3/5] Creating windows and composite stability labels...", flush=True)

all_features = [c for c in df_wide.columns if c != 'time']
X_list, y_list, scores_list = [], [], []
n = len(df_wide)

for i in range(0, n - 2*WINDOW_SIZE, STEP_SIZE):
    window = df_wide.iloc[i:i+WINDOW_SIZE]
    future = df_wide.iloc[i+WINDOW_SIZE:i+2*WINDOW_SIZE]

    feats = {}
    for col in all_features:
        vals = window[col].values
        feats[f'{col}_mean'] = np.mean(vals)
        feats[f'{col}_std'] = np.std(vals)
        feats[f'{col}_min'] = np.min(vals)
        feats[f'{col}_max'] = np.max(vals)
        feats[f'{col}_range'] = np.max(vals) - np.min(vals)
        x = np.arange(len(vals))
        feats[f'{col}_slope'] = np.polyfit(x, vals, 1)[0] if np.std(vals) > 1e-9 else 0.0

    # Start of scoring logic for each window 'i'
    bus_scores = []
    inter_scores = []

    for bus in buses:
        v = future[f'voltage_pu_{bus}'].values
        f = future[f'frequency_{bus}'].values
        r = future[f'rocof_{bus}'].values
        a = future[f'angle_deg_{bus}'].values
        g = future[f'gen_p_{bus}'].values
        l = future[f'load_p_{bus}'].values
        d = future[f'delay_{bus}'].values

        # Individual Bus Scoring
        v_score = max(0, 1 - np.max(np.abs(v - 1.0)) / 0.05)
        f_score = max(0, 1 - np.max(np.abs(f - 50.0)) / 0.1)
        r_score = max(0, 1 - np.max(np.abs(r)) / 0.1)
        a_score = max(0, 1 - np.max(np.abs(a)) / 10.0)
        p_score = max(0, 1 - np.mean(np.abs(g - l)) / 5.0)
        d_score = max(0, 1 - np.mean(d) / 0.3)

        bus_score = np.mean([v_score, f_score, r_score, a_score, p_score, d_score])
        bus_scores.append(bus_score)

    # Inter-area Connection Scoring
    for pair in [('MG1','MG2'), ('MG2','MG3'), ('MG1','MG3')]:
        a1 = future[f'angle_deg_{pair[0]}'].values
        a2 = future[f'angle_deg_{pair[1]}'].values
        diff = np.max(np.abs(a1 - a2))
        inter_scores.append(max(0, 1 - diff / 10.0))

    # System power balance score
    pimb = np.mean(np.abs(future['total_power_imbalance'].values))
    pimb_score = max(0, 1 - pimb / 5.0)
    # Overall stability score (0 to 1)
    overall_score = np.mean(bus_scores + inter_scores + [pimb_score])

    scores_list.append(overall_score)
    X_list.append(feats)

    if len(X_list)>= MAX_SAMPLES:
        break

"""### Composite Stability Index (data-driven but physically meaningful)

For each bus, compute normalized deviation scores
Lower score = more unstable / poor quality

Normalize each metric to a 0-1 score (1 = perfect, 0 = worst in data)
Using expected ranges based on power system standards
"""

# ==============================================================================
# POST-LOOP EVALUATION
# ==============================================================================

# Check if 'scores_list' is defined, if not, initialize it to an empty list
# This prevents NameError if the preceding cell was not run, but actual data will be missing.
# For correct execution, ensure the cell '3. WINDOWS & COMPOSITE STABILITY LABEL' (kNS_WTVoVaGd) is run first.
if 'scores_list' not in locals() and 'scores_list' not in globals():
    scores_list = []
    print("Warning: 'scores_list' was not found. Please ensure the preceding cell (kNS_WTVoVaGd) has been run.")

scores = np.array(scores_list)

# CRITICAL CHECK: If scores is empty, subsequent calculations will fail or be meaningless.
if scores.size == 0:
    print("Error: The 'scores' array is empty. Please run the cell '3. WINDOWS & COMPOSITE STABILITY LABEL' (kNS_WTVoVaGd) to generate data before executing this cell.")
    # Exit or return to prevent further errors on empty data
    # For a notebook, we can print the message and effectively stop further meaningful calculations.
else:
    threshold = np.percentile(scores, 60)
    y = np.where(scores >= threshold, 1, 0)

    # X_list is populated in the same loop as scores_list in kNS_WTVoVaGd
    if 'X_list' not in locals() and 'X_list' not in globals():
        X_list = []
        print("Warning: 'X_list' was not found. Please ensure the preceding cell (kNS_WTVoVaGd) has been run.")

    X_df = pd.DataFrame(X_list)

    print(f"Windows: {len(X_df)}, Features: {X_df.shape[1]}", flush=True)
    print(f"Score range: [{scores.min():.4f}, {scores.max():.4f}], threshold={threshold:.4f}", flush=True)
    print(f"Stable={np.sum(y==1)}, Unstable={np.sum(y==0)} ({np.mean(y)*100:.1f}% stable)", flush=True)

    X_df = X_df.loc[:, X_df.std() > 1e-9]
    print(f"After removing constants: {X_df.shape[1]} features", flush=True)

"""============================================================
4. SPLIT & SCALE
============================================================

"""

print("\n[4/5] Splitting and scaling...", flush=True)
X_train, X_test, y_train, y_test = train_test_split(
    X_df, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y
)
scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)
print(f"Train: {len(X_train)}, Test: {len(X_test)}", flush=True)

"""============================================================
5. MODELS
============================================================

"""

print("\n[5/5] Training models...", flush=True)

models = {
    'Logistic Regression': LogisticRegression(max_iter=500, random_state=RANDOM_STATE, class_weight='balanced'),
    'SVM (Linear)': SVC(kernel='linear', C=0.5, probability=True, random_state=RANDOM_STATE, class_weight='balanced', max_iter=2000),
    'SVM (RBF)': SVC(kernel='rbf', C=1.0, gamma='scale', probability=True, random_state=RANDOM_STATE, class_weight='balanced', max_iter=2000),
    'KNN (k=5)': KNeighborsClassifier(n_neighbors=5, n_jobs=-1),
    'KNN (k=10)': KNeighborsClassifier(n_neighbors=10, weights='distance', n_jobs=-1),
    'Naive Bayes': GaussianNB(),
    'Decision Tree': DecisionTreeClassifier(max_depth=10, random_state=RANDOM_STATE, class_weight='balanced'),
    'Random Forest': RandomForestClassifier(n_estimators=50, max_depth=12, random_state=RANDOM_STATE, class_weight='balanced', n_jobs=-1),
    'AdaBoost': AdaBoostClassifier(n_estimators=50, learning_rate=0.1, random_state=RANDOM_STATE),
    'Gradient Boosting': GradientBoostingClassifier(n_estimators=50, max_depth=4, learning_rate=0.1, random_state=RANDOM_STATE),
    'XGBoost': XGBClassifier(n_estimators=50, max_depth=5, learning_rate=0.1, random_state=RANDOM_STATE, use_label_encoder=False, eval_metric='logloss', n_jobs=-1),
    'ANN (Small)': MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=300, random_state=RANDOM_STATE, early_stopping=True, validation_fraction=0.1, n_iter_no_change=15),
    'ANN (Medium)': MLPClassifier(hidden_layer_sizes=(128, 64, 32), max_iter=300, random_state=RANDOM_STATE, early_stopping=True, validation_fraction=0.1, n_iter_no_change=15),
}

results = []
roc_data = {}

for name, model in models.items():
    print(f"  -> {name}...", flush=True, end=' ')
    t0 = time.time()

    if name in ['Random Forest', 'Decision Tree', 'AdaBoost', 'Gradient Boosting', 'XGBoost', 'Naive Bayes']:
        X_tr, X_te = X_train.values, X_test.values
    else:
        X_tr, X_te = X_train_s, X_test_s

    model.fit(X_tr, y_train)
    t = time.time() - t0

    y_pred = model.predict(X_te)
    y_prob = model.predict_proba(X_te)[:, 1] if hasattr(model, 'predict_proba') else None

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, zero_division=0)
    rec = recall_score(y_test, y_pred, zero_division=0)
    f1 = f1_score(y_test, y_pred, zero_division=0)
    mcc = matthews_corrcoef(y_test, y_pred)
    roc = roc_auc_score(y_test, y_prob) if y_prob is not None else np.nan

    if y_prob is not None:
        roc_data[name] = (y_prob, roc)

    results.append({'Model': name, 'Accuracy': acc, 'Precision': prec, 'Recall': rec,
                   'F1-Score': f1, 'ROC-AUC': roc, 'MCC': mcc, 'Train_Time_s': t})
    print(f"Acc={acc:.4f} F1={f1:.4f} ROC={roc:.4f} Time={t:.2f}s", flush=True)

results_df = pd.DataFrame(results).sort_values('F1-Score', ascending=False).reset_index(drop=True)

"""============================================================
6. SAVE
============================================================

"""

print("\nSaving results...", flush=True)
results_df.to_csv(os.path.join(OUTPUT_DIR, 'model_comparison_results.csv'), index=False)

with open(os.path.join(OUTPUT_DIR, 'report.txt'), 'w') as f:
    f.write("="*65 + "\n")
    f.write("MICROGRID SMALL-SIGNAL STABILITY ANALYSIS\n")
    f.write("ML / DL Algorithm Comparison Report\n")
    f.write("="*65 + "\n\n")
    f.write(f"Dataset: {DATA_PATH}\n")
    f.write(f"Subsample: every {SUBSAMPLE_EVERY}th row\n")
    f.write(f"Window size: {WINDOW_SIZE} steps\n")
    f.write(f"Features: {X_df.shape[1]}\n")
    f.write(f"Samples: {len(X_df)} (Stable={np.sum(y==1)}, Unstable={np.sum(y==0)})\n\n")

    f.write("-"*65 + "\n")
    f.write("RANKING BY F1-SCORE\n")
    f.write("-"*65 + "\n\n")
    for i, row in results_df.iterrows():
        f.write(f"{i+1:2d}. {row['Model']}\n")
        f.write(f"    Acc={row['Accuracy']:.4f} Prec={row['Precision']:.4f} Rec={row['Recall']:.4f}\n")
        f.write(f"    F1={row['F1-Score']:.4f} ROC={row['ROC-AUC']:.4f} MCC={row['MCC']:.4f}\n")
        f.write(f"    Time={row['Train_Time_s']:.2f}s\n\n")

"""### Plot 1: Performance bars

"""

fig, axes = plt.subplots(2, 3, figsize=(15, 9))
fig.suptitle('Microgrid Stability - Model Performance Comparison', fontsize=14, fontweight='bold')
metrics = ['Accuracy', 'Precision', 'Recall', 'F1-Score', 'ROC-AUC', 'MCC']
colors = plt.cm.tab20(np.linspace(0, 1, len(results_df)))
for ax, m in zip(axes.flat, metrics):
    ax.barh(results_df['Model'], results_df[m], color=colors)
    ax.set_xlabel(m, fontsize=9)
    ax.set_xlim(0, 1.05)
    ax.invert_yaxis()
    ax.grid(axis='x', alpha=0.3)
    for bar, val in zip(ax.patches, results_df[m]):
        if not np.isnan(val):
            ax.text(val + 0.01, bar.get_y() + bar.get_height()/2, f'{val:.3f}', va='center', fontsize=6)
plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.savefig(os.path.join(OUTPUT_DIR, 'performance_comparison.png'), dpi=300, bbox_inches='tight')
plt.close()

"""### Plot 2: ROC curves

"""

plt.figure(figsize=(10, 7))
for name in roc_data:
    y_prob, roc_auc = roc_data[name]
    fpr, tpr, _ = roc_curve(y_test, y_prob)
    plt.plot(fpr, tpr, label=f'{name} (AUC={roc_auc:.3f})', linewidth=1.2)
plt.plot([0,1], [0,1], 'k--', linewidth=1)
plt.xlabel('False Positive Rate', fontsize=12)
plt.ylabel('True Positive Rate', fontsize=12)
plt.title('ROC Curves - All Models', fontsize=14, fontweight='bold')
plt.legend(loc='lower right', fontsize=7, ncol=2)
plt.grid(alpha=0.3)
plt.savefig(os.path.join(OUTPUT_DIR, 'roc_curves.png'), dpi=300, bbox_inches='tight')
plt.close()

"""### Plot 3: Heatmap

"""

plt.figure(figsize=(8, 7))
hm = results_df.set_index('Model')[metrics].sort_values('F1-Score', ascending=True)
sns.heatmap(hm, annot=True, fmt='.3f', cmap='RdYlGn', vmin=0, vmax=1, linewidths=0.5)
plt.title('Performance Heatmap', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, 'performance_heatmap.png'), dpi=300, bbox_inches='tight')
plt.close()

"""### Plot 4: Train time

"""

plt.figure(figsize=(10, 6))
plt.barh(results_df['Model'], results_df['Train_Time_s'], color='coral', edgecolor='darkred')
plt.xlabel('Training Time (seconds)', fontsize=12)
plt.title('Training Time Comparison', fontsize=14, fontweight='bold')
plt.gca().invert_yaxis()
plt.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, 'train_time.png'), dpi=300, bbox_inches='tight')
plt.close()

"""### Plot 5: Confusion matrix (best model)

"""

best_name = results_df.iloc[0]['Model']
best_model = models[best_name]
X_te = X_test.values if best_name in ['Random Forest','Decision Tree','AdaBoost','Gradient Boosting','XGBoost','Naive Bayes'] else X_test_s
y_pred_best = best_model.predict(X_te)
cm = confusion_matrix(y_test, y_pred_best)
plt.figure(figsize=(5, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Unstable','Stable'], yticklabels=['Unstable','Stable'])
plt.title(f'Best Model: {best_name}', fontsize=13, fontweight='bold')
plt.ylabel('True Label', fontsize=11)
plt.xlabel('Predicted Label', fontsize=11)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, 'confusion_matrix.png'), dpi=300, bbox_inches='tight')
plt.close()

print("\n" + "="*60, flush=True)
print("FINAL SUMMARY", flush=True)
print("="*60, flush=True)
print(results_df[['Model','Accuracy','F1-Score','ROC-AUC','MCC']].head(5).to_string(index=False), flush=True)
print(f"\nBest Model: {best_name}", flush=True)
print(f"  Accuracy:  {results_df.iloc[0]['Accuracy']:.4f}", flush=True)
print(f"  F1-Score:  {results_df.iloc[0]['F1-Score']:.4f}", flush=True)
print(f"  ROC-AUC:   {results_df.iloc[0]['ROC-AUC']:.4f}", flush=True)
print(f"  MCC:       {results_df.iloc[0]['MCC']:.4f}", flush=True)
print(f"\nAll outputs saved to: {OUTPUT_DIR}", flush=True)
print("="*60, flush=True)